### ISSUE TITLE
Setting up kanban board

### ISSUE THREAD

**Issue by TracyMuso** [TracyMuso/Capstone-project-2#21]
https://github.com/elfin-git/Capstone-project-2/projects/1
There are two people in our team

**Comment by rustam-tolipov** [comment]
## Hello team👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
